name: dart_hello_server
description: A web server
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.5.0
  # shelf: ^0.7.5
  http_server: ^0.9.8
  logging: ^0.11.3+2
  jaguar: ^2.4.36

dev_dependencies:
  pedantic: ^1.8.0
